#!/bin/bash



i=2
linies=`wc -l < esportistes`
linia=`head -1 esportistes | tail -1`
edat=`echo $linia | cut -d: -f4`
min=$edat
pmin=0


while [ $i -le $linies ]
do
	linia=`head -$i esportistes | tail -1`
	edat=`echo $linia | cut -d: -f4`
	if [ $edat -eq $min ];
	then
		min=$edat
		pmin=$i
		linia=`head -$pmin esportistes | tail -1`
		echo $linia | cut -d: -f 1,2,3,4 >> menor
	fi
	if [ $edat -lt $min ];
	then
		min=$edat
		pmin=$i
		linia=`head -$pmin esportistes | tail -1`
		echo $linia | cut -d: -f 1,2,3,4 > menor
	fi
		
	let i=i+1
done


